---
- name: Download Consul
  get_url:
    url: https://releases.hashicorp.com/consul/0.6.0/consul_0.6.0_linux_amd64.zip
    dest: /tmp/consul.zip
  when: consul_bin.stat.exists == false

- name: Install unzip
  apt: name=unzip

- name: unzip consul
  unarchive:
    src: /tmp/consul.zip
    dest: /bin
    copy: no

- name: remove zip
  file:
    path: /tmp/consul.zip
    state: absent