---
- stat: path=/bin/consul
  register: consul_bin

- include: install.yml
  when: consul_bin.stat.exists == false

- name: Create data dir
  file:
    path: /var/consul
    state: directory

- name: Consult config
  template:
    src: config.json.j2
    dest: /etc/consul.json
  register: consul_config

- name: Install systemd unit for consul
  template: 
    src: consul.service
    dest: /etc/systemd/system/consul.service
  register: consul_service

- name: notify systemd of config changes
  shell: systemctl daemon-reload && systemctl enable consul.service
  when: consul_service.changed

- name: Restart consul when config changes
  shell: systemctl restart consul
  when: consul_service.changed or consul_config.changed

- name: Install consul as a resolver
  lineinfile:
    insertbefore: EOF
    dest: /etc/resolvconf/resolv.conf.d/head
    regexp: "{{ ansible_eth0.ipv4.address }}"
    line: "nameserver {{ ansible_eth0.ipv4.address }}"
    state: present
    create: yes
  register: resolver

- name: Restart systemd-resolved.service
  shell: resolvconf -u
  when: resolver.changed

