---
- name: Install Service unit for docker swarm
  template: 
    src: swarm.service
    dest: /etc/systemd/system/swarm.service
  notify: restart swarm

- name: Install Upstart unit for docker swarm manager
  template: 
    src: swarm_manager.service
    dest: /etc/systemd/system/swarm_manager.service
  notify: restart swarm_manager
