---
- stat: path=/bin/flanneld
  register: flanneld_bin

- include: install.yml
  when: flanneld_bin.stat.exists == false

- name: Service file
  template:
    src: flannel.service
    dest: /etc/systemd/system/flannel.service
  register: flannel_service

- name: notify systemd of config changes
  shell: "{{item}}"
  with_items:
    - "systemctl daemon-reload"
    - "systemctl enable flannel.service"
  when: flannel_service.changed


- name: Restart flannel
  shell: "systemctl restart flannel"
  when: flannel_service.changed
