---
- stat: path=/bin/fleetd
  register: fleetd_bin

- include: install.yml
  when: fleetd_bin.stat.exists == false

- name: Create service file
  template:
    src: fleet.service
    dest: /etc/systemd/system/fleet.service
  register: fleet_service

- name: Create socket service file
  template:
    src: fleet.socket
    dest: /etc/systemd/system/fleet.socket
  register: fleet_socket

- name: Config file
  template:
    src: fleet.conf
    dest: /etc/fleet.conf
  register: fleet_config


- name: notify systemd of config changes
  shell: "{{item}}"
  with_items:
    - "systemctl daemon-reload"
    - "systemctl enable fleet.socket"
    - "systemctl enable fleet.service"
  when: fleet_service.changed or fleet_socket.changed


- name: Restart fleet
  shell: "systemctl restart fleet"
  when: fleet_service.changed or fleet_socket.changed or fleet_config.changed
