---
- name: Install Docker apt gpg key
  apt_key: 
    keyserver: 'hkp://p80.pool.sks-keyservers.net:80'
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: add Docker apt source
  apt_repository:
    repo: "{{ docker_repo }}"

- name: Grab kernel version
  shell: 'uname -r'
  changed_when: false
  register: kernel_version
- name: Install kernal extras
  apt:
    name: 'linux-image-extra-{{kernel_version.stdout}}'

- name: Install Docker
  apt:
    name: docker-engine
        
- name: Listen on tcp
  template:
    src: docker-tcp.service
    dest: /etc/systemd/system/docker-tcp.socket
  register: docker_restart

- name: Docker service
  template:
    src: docker.service
    dest: /lib/systemd/system/docker.service
  register: docker_restart

- name: notify systemd of config changes
  shell: systemctl daemon-reload && systemctl restart docker
  when: docker_restart.changed
