---

#Setup cconstantine user
- hosts: all
  remote_user: "{{ rootlike_user }}"
  sudo: yes
  tasks:
  - hostname: name="{{ inventory_hostname_short }}"
  - name: Create group for passwordless users
    group:
      name: passwordless_sudo
      state: present
  - name: Allow passwordless sudo
    lineinfile:
      insertafter: EOF
      dest: /etc/sudoers
      line: '%passwordless_sudo ALL=(ALL) NOPASSWD: ALL'
      regexp: 'passwordless_sudo'
      state: present

  - name: Create cconstantine user
    user:
      name: cconstantine
      groups: admin,passwordless_sudo
      append: true
      shell: /bin/bash

  - name: Install authorized_key
    authorized_key:
      user: cconstantine
      key: "{{ lookup('file', item) }}"
    with_fileglob:
      - ssh_keys/*.pub
      