- hosts: control
  sudo: yes
  serial: 1
  roles:
    - role: consul

- hosts: control
  sudo: yes
  roles:
    - role: etcd
    - role: fleet
      fleet_type: control
    - role: flannel
    - role: docker
