
# Install some basic things
- hosts: silly_pants
  sudo: yes
  tasks:
    - name: Install some basic tools
      apt:
        name: "{{ item }}"
      with_items:
        - awscli
        - htop
  roles:
    - role: tubes
    - role: docker

- hosts: swarm
  sudo: yes
  roles:
    - role: consul
    - role: docker
#    - role: swarm