
# Install some basic things
- hosts: all
  sudo: yes
  tasks:
    - name: Update sources
      apt:
        update_cache: true
    - name: Install some basic tools
      apt:
        name: "{{ item }}"
      with_items:
        - htop
        - awscli

- hosts: swarm
  sudo: yes
  roles:
    - role: consul
    - role: docker
    - role: swarm